# Site settings
title: SOKOL Šestajovice
email: starosta@sokolsestajovice.cz
description: > # this means to ignore newlines until "baseurl:"
  Sokol – sport pro všechny!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.sokolsestajovice.cz" # the base hostname & protocol for your site
phone: 605204967

defaults:
   - scope:
       path: ""
       type: posts
     values:
       layout: post

prose:
  ignore: ['index.md','kalendar.md','o-sokole.md','clenstvi.md','struktura.md','kontakt.md','archiv.md','oddily','images','files', '_config.yml', '_data', '_includes', '_layouts','_sass','assets','galerie','.gitignore','CNAME','favicon.ico','feed.xml']
  metadata:
    _posts:
      - name: "title"
        field:
          element: "text"
          label: "Název"
      - name: "excerpt"
        field:
          element: "textarea"
          label: "Krátký popis"

future: true